spring:
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB}
  jpa:
    hibernate:
      ddl-auto: create-drop
  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
      max-file-size: 1MB
springdoc:
  swagger-ui:
    path: /swagger-docs
aws:
  s3:
    bucket: ${AWS_BUCKET_NAME}
    access-key-id: ${AWS_ACCESS-KEY_ID}
    access-key-secret: ${AWS_ACCESS-KEY_SECRET}
