spring:
  datasource:
    username: omni_renter
    password: omni_renter
    url: jdbc:postgresql://localhost:5432/omni_rental_db
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
      max-file-size: 1MB
springdoc:
  swagger-ui:
    path: /swagger-docs
